name: Publish Python Package to PyPI

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can change this to the version you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools twine

    - name: Build distribution
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload package to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install twine
        twine upload dist/* --username $TWINE_USERNAME --password $TWINE_PASSWORD
